package do_hoa;

import do_an.QuanLyThuVien;
import do_an.The;
import java.awt.Color;
import do_an.sach;
import do_an.Sinh_Vien;
import java.awt.Font;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
public class GUI extends javax.swing.JFrame implements Runnable{
    public static int i=0;
    
          public static String chuanHoaTen(String ten) {
    String[] arr = ten.split("\\s+");
    StringBuilder sb = new StringBuilder();
    for (String s : arr) {
        if (s.length() > 0) {
            sb.append(Character.toUpperCase(s.charAt(0)));
            sb.append(s.substring(1).toLowerCase());
            sb.append(" ");
        }
    }
    return sb.toString().trim();
}
    public static boolean isValidDateFormat(String input) {
        // Định dạng regex cho "dd/mm/yyyy"
        String regex = "^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/(\\d{4})$";

        // Tạo đối tượng Pattern
        Pattern pattern = Pattern.compile(regex);

        // Tạo đối tượng Matcher
        Matcher matcher = pattern.matcher(input);

        // Kiểm tra xem chuỗi có khớp với regex hay không
        if (!matcher.matches()) {
            return false;
        }

        // Kiểm tra năm nhuận
        int day = Integer.parseInt(matcher.group(1));
        int month = Integer.parseInt(matcher.group(2));
        int year = Integer.parseInt(matcher.group(3));

        if (month == 2) {
            // Kiểm tra tháng 2 có nằm trong khoảng 1-29 ngày (nếu là năm nhuận)
            if ((year % 4 == 0 && year % 100 != 0) || (year % 400 == 0)) {
                return day >= 1 && day <= 29;
            } else {
                return day >= 1 && day <= 28;
            }
        }

        return true;
    }
            QuanLyThuVien ds= new QuanLyThuVien();
            
            int hour,minute,second;
            DefaultTableModel model;    
            DefaultTableModel model2;    
            DefaultTableModel model3;    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        Thread t= new Thread(this);
        t.start();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
         model=  new DefaultTableModel();
         model2 = new DefaultTableModel();
         model3 = new DefaultTableModel();
        table.getTableHeader().setReorderingAllowed(false);
        
        model.addColumn("Mã phiếu");
        model.addColumn("Họ tên");
        model.addColumn("Tuổi");
        model.addColumn("Lớp");
        model.addColumn("Ngày mượn");
        model.addColumn("Ngày trả");
        model.addColumn("Mã sách");
        model.addColumn("Tên sách");
        model.addColumn("Tác giả");
         model2.addColumn("Mã sách");
         model2.addColumn("Tên sách");
         model2.addColumn("Tác giả");
         model3.addColumn("Họ Tên");
         model3.addColumn("Tuổi");
         model3.addColumn("Lớp");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtextmaphieu = new javax.swing.JTextField();
        jtextname = new javax.swing.JTextField();
        jtexttuoi = new javax.swing.JTextField();
        jtextlop = new javax.swing.JTextField();
        jtextday1 = new javax.swing.JTextField();
        jtextday2 = new javax.swing.JTextField();
        jtextnames = new javax.swing.JTextField();
        jtextnametg = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnshow = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jtextmasach = new javax.swing.JTextField();
        btnclear = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        hour12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        OPEN = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        SAVE = new javax.swing.JMenu();

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel12.setText("jLabel12");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ THƯ VIỆN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("ĐỌC FILE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("GHI FILE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("THOÁT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 204));
        jButton4.setText("TÌM THEO TÊN SÁCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 204));
        jButton5.setText("TìM THEO TÊN TÁC GIẢ ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 204));
        jButton6.setText("TÌM THEO TÊN SINH VIÊN");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jLayeredPane2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        jLayeredPane2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton4, jButton5, jButton6});

        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 840, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("CHỨC NĂNG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 100, 25));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("MÃ PHIẾU :");

        jLabel3.setText("HỌ TÊN : ");

        jLabel4.setText("TUỔI :");

        jLabel5.setText("LỚP :");

        jLabel6.setText("NGÀY MƯỢN :");

        jLabel7.setText("TÊN TÁC GIẢ :");

        jLabel8.setText("NGÀY TRẢ :");

        jLabel9.setText("TÊN SÁCH :");

        jtextmaphieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextmaphieuActionPerformed(evt);
            }
        });

        jtexttuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtexttuoiActionPerformed(evt);
            }
        });

        jtextday1.setForeground(new java.awt.Color(153, 153, 153));
        jtextday1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtextday1.setText("DD/MM/YYYY");
        jtextday1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtextday1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtextday1MouseClicked(evt);
            }
        });
        jtextday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextday1ActionPerformed(evt);
            }
        });

        jtextday2.setForeground(new java.awt.Color(153, 153, 153));
        jtextday2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtextday2.setText("DD/MM/YYYY");
        jtextday2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtextday2MouseClicked(evt);
            }
        });
        jtextday2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextday2ActionPerformed(evt);
            }
        });

        jtextnametg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextnametgActionPerformed(evt);
            }
        });

        btnthem.setText("THÊM");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setText("XÓA");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnshow.setText("SHOW ALL");
        btnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowActionPerformed(evt);
            }
        });

        jLabel11.setText("MÃ SÁCH : ");

        jtextmasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextmasachActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnsua.setText("SỬA");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtextmaphieu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtextname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtexttuoi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtextlop, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtextday1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtextday2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtextnames, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtextnametg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnthem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnxoa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnshow, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtextmasach, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnclear, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnsua, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addGap(24, 24, 24)
                                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtextmaphieu)
                                        .addComponent(jtextname, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtexttuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                            .addGap(70, 70, 70)
                                            .addComponent(jtextlop, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel6))))
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtextnames, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtextmasach, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtextday2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtextday1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtextnametg, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                            .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(34, 34, 34)
                                            .addComponent(btnshow, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextmaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtexttuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextlop, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextday1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextday2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextmasach, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextnames, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextnametg, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnshow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa)
                    .addComponent(btnsua))
                .addGap(29, 29, 29))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel11, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, jtextday1, jtextday2, jtextlop, jtextmaphieu, jtextmasach, jtextname, jtextnames, jtextnametg, jtexttuoi});

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnsua, btnthem, btnxoa});

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 60, 420, 540));

        hour12.setBackground(new java.awt.Color(204, 0, 51));
        hour12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        hour12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hour12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(hour12, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 620, 420, 200));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("BẢNG THÔNG TIN");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 6, 496, 48));

        table.setBackground(new java.awt.Color(255, 102, 102));
        table.setForeground(new java.awt.Color(255, 0, 102));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 590));

        OPEN.setText("FILE");

        jMenuItem4.setText("OPEN");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        OPEN.add(jMenuItem4);

        jMenuItem5.setText("SAVE");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        OPEN.add(jMenuItem5);

        jMenuBar2.add(OPEN);

        SAVE.setText("EDIT");
        jMenuBar2.add(SAVE);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextday1ActionPerformed
       
    }//GEN-LAST:event_jtextday1ActionPerformed

    private void jtextday1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtextday1MouseClicked
        jtextday1.setText("");
        jtextday1.setForeground(Color.black);
    }//GEN-LAST:event_jtextday1MouseClicked

    boolean checkFill(){
     if (jtextmaphieu.getText().equals("")) return false;
     if (jtextname.getText().equals("")) return false;
     if (jtexttuoi.getText().equals("")) return false;
     if (jtextlop.getText().equals("")) return false;
     if (jtextday1.getText().equals("DD/MM/YYYY")) return false;
     if (jtextday2.getText().equals("DD/MM/YYYY")) return false;
     if (jtextnames.getText().equals("")) return false;
     if (jtextnametg.getText().equals("")) return false;
     return true;
 }
     public static boolean compareDates(String date1, String date2) throws ParseException {
        // Định dạng ngày tháng
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        // Chuyển đổi chuỗi ngày tháng thành đối tượng Date
        Date dateObj1 = sdf.parse(date1);
        Date dateObj2 = sdf.parse(date2);

        // So sánh hai đối tượng Date
        return dateObj1.before(dateObj2);
    }
     boolean checkbf(){
         try {
             boolean res=compareDates(jtextday1.getText(), jtextday2.getText());
             return res;
         } catch (Exception e) {
         }
         return false;
     }
    boolean checkTuoi(){
        int a=0;
        try {
            a=Integer.parseInt(jtexttuoi.getText());
           
        } catch (Exception e) {
            return false;
        }
        return true;
    }

    public static boolean isValidName(String name) {
    for (int i = 0; i < name.length(); i++) {
        char c = name.charAt(i);
        if (isSpecialCharacter(c)) {
            return false;
        }
    }

    return true;
}

public static boolean isSpecialCharacter(char c) {
    return !(Character.isLetter(c) || Character.isWhitespace(c));
}

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        if(btnthem.getText().equals("UPDATE")) ds.xoaMa(maDeXoa);
        if (!checkFill()){
            JOptionPane.showMessageDialog(rootPane, "BẠN VẪN CHƯA NHẬP VÀO Ô NÀO ĐÓ !!");
        }else if(!isValidDateFormat(jtextday1.getText())){
            JOptionPane.showMessageDialog(rootPane,"Ngày mượn của bạn nhập sại định dạng rồi !!" );
            jtextday1.setForeground(Color.GRAY.brighter());
            jtextday1.setText("DD/MM/YYYY");
        }else if (!isValidDateFormat(jtextday2.getText())){
                        JOptionPane.showMessageDialog(rootPane,"Ngày trả của bạn nhập sại định dạng rồi !!" );
        jtextday2.setForeground(Color.GRAY.brighter());
            jtextday2.setText("DD/MM/YYYY"); 
        }else if (!checkbf()){
             JOptionPane.showMessageDialog(rootPane, "Ngày mượn phải trước ngày trả chứ nhỉ ? :v " );
             jtextday1.setForeground(Color.GRAY.brighter());
            jtextday1.setText("DD/MM/YYYY");
        }else if (!checkTuoi() || Integer.parseInt(jtexttuoi.getText())<0){
            JOptionPane.showMessageDialog(rootPane, "BẠN NHẬP SAI ĐỊNH DẠNG TUỔI RỒI ");
            jtexttuoi.setText("");
        }else if(!ds.check(jtextmaphieu.getText()))
        {
        JOptionPane.showMessageDialog(rootPane, "MÃ PHIẾU NÀY ĐÃ TỒN TẠI");
        jtextmaphieu.setText("");
        }else if(!ds.checkmaSach(jtextmasach.getText())){
         JOptionPane.showMessageDialog(rootPane, "MÃ SÁCH NÀY ĐÃ TỒN TẠI");
        jtextmasach.setText("");
        }else if (!isValidName(jtextname.getText())|| !isValidName(jtextnametg.getText())){
            JOptionPane.showMessageDialog(rootPane, "NHẬP SAI ĐỊNH DẠNG TÊN");
        }
        else {
             
            sach sc = new sach(jtextmasach.getText() , chuanHoaTen(jtextnames.getText()), chuanHoaTen(jtextnametg.getText()));
            Sinh_Vien sv= new Sinh_Vien(chuanHoaTen(jtextname.getText()), Integer.parseInt(jtexttuoi.getText()), jtextlop.getText());
          
            The the= new The(jtextmaphieu.getText(), jtextday1.getText(), jtextday2.getText(), sc, sv);

        ds.them(the);
        if (btnthem.getText().equals("UPDATE")){
              
            btnthem.setText("THÊM");
            dung();
              }else{
            The th= ds.getThe(i++);
    model.addRow(new Object[]{
        
    th.getMaPhieu(),th.getSinhVien().getHoTen(),th.getSinhVien().getTuoi(),th.getSinhVien().getLop(),th.getNgayMuon(),th.getNgayTra(),th.getSach().getMaSach(),th.getSach().getTenSach(),th.getSach().getTacGia()
    });
table.setModel(model);
        }
       
    
      
       
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void jtextday2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextday2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextday2ActionPerformed

    private void jtextday2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtextday2MouseClicked
    jtextday2.setText("");
        jtextday2.setForeground(Color.black);
    }//GEN-LAST:event_jtextday2MouseClicked

    private void jtexttuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtexttuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtexttuoiActionPerformed

    private void jtextmasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextmasachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextmasachActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        jtextmaphieu.setText("");
        jtextname.setText("");
        jtextnames.setText("");
        jtextnametg.setText("");
        jtextday1.setForeground(Color.GRAY.brighter());
        jtextday1.setText("DD/MM/YYYY");
                jtextday2.setForeground(Color.GRAY.brighter());

        jtextday2.setText("DD/MM/YYYY");
       jtextmasach.setText("");
        jtexttuoi.setText("");
        jtextlop.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        
    
        String ma=JOptionPane.showInputDialog("Nhập mã phiếu bạn cần xóa: ");
        if (ma!=null){
              if ( ds.check(ma)==true){
            JOptionPane.showMessageDialog(rootPane, "MÃ THẺ KHÔNG TỒN TẠI");
        }else{
            i--;
           ds.xoaMa(ma);
            
            dung();
            JOptionPane.showMessageDialog(rootPane, "XÓA THÀNH CÔNG");
            
                 
                  
        }
        }
      
        
    }//GEN-LAST:event_btnxoaActionPerformed

    private void jtextmaphieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextmaphieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextmaphieuActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(this);
        if (jfc.getSelectedFile()==null){
            JOptionPane.showMessageDialog(rootPane, "BẠN CHƯA CHỌN FILE NÀO ");
        }else{
             try {
            FileInputStream is = new FileInputStream(jfc.getSelectedFile().getAbsolutePath());
            ObjectInputStream ois = new ObjectInputStream(is);
           ds.set((ArrayList<The>) ois.readObject());
            JOptionPane.showMessageDialog(rootPane, "Đọc thành công");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(QuanLyThuVien.class.getName()).log(Level.SEVERE, null, ex);
                   JOptionPane.showMessageDialog(rootPane, "Đọc không thành công");

        } catch (IOException ex) {
            Logger.getLogger(QuanLyThuVien.class.getName()).log(Level.SEVERE, null, ex);
                   JOptionPane.showMessageDialog(rootPane, "Đọc không thành công");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyThuVien.class.getName()).log(Level.SEVERE, null, ex);
                           JOptionPane.showMessageDialog(rootPane, "Đọc không thành công");

        }
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(this);
        if (jfc.getSelectedFile()==null){
            JOptionPane.showMessageDialog(rootPane, "BẠN CHƯA CHỌN FILE NÀO ");
        }else{
        try {
            FileOutputStream os = new FileOutputStream(jfc.getSelectedFile().getAbsolutePath());
            ObjectOutputStream oos = new ObjectOutputStream(os);
            oos.writeObject(ds.getDS());
            oos.close();
            os.close();
            JOptionPane.showMessageDialog(rootPane, "GHI THÀNH CÔNG");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(QuanLyThuVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
           
            Logger.getLogger(QuanLyThuVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String tensach=JOptionPane.showInputDialog("Nhập vào tên sách: ");
        if (tensach!=null) {
        
        
        model2.setRowCount(0);
        ArrayList<The> th= ds.getDS();
        int ok=0;
        for(The t:th){
           
            if ((t.getSach().getTenSach()).toLowerCase().contains(tensach.toLowerCase())){
                ok=1;
                model2.addRow(new Object[]{
                t.getSach().getMaSach(),t.getSach().getTenSach(),t.getSach().getTacGia()
                       
                });
             
            }  table.setModel(model2);
        }
        if  (ok==0){
            JOptionPane.showMessageDialog(rootPane, "TÊN SÁCH KHÔNG TỒN TẠI");
        }
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String ten=JOptionPane.showInputDialog("Nhập vào tên sinh viên: ");
        if (ten!=null){
             model3.setRowCount(0);
        ArrayList<The> th= ds.getDS();
        int ok=0;
           for(The t:th){
            
            if ((t.getSinhVien().getHoTen()).toLowerCase().contains(ten.toLowerCase())){
                ok=1;
                model3.addRow(new Object[]{
                t.getSinhVien().getHoTen(),t.getSinhVien().getTuoi(),t.getSinhVien().getLop()
                       
                });
               table.setModel(model3);
            }
        }
           if  (ok==0){
            JOptionPane.showMessageDialog(rootPane, "TÊN SÁCH KHÔNG TỒN TẠI");
        }
        }
      
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(this);
        if (jfc.getSelectedFile()==null){
            JOptionPane.showMessageDialog(rootPane, "BẠN CHƯA CHỌN FILE NÀO ");
        }else{
             try {
            FileInputStream is = new FileInputStream(jfc.getSelectedFile().getAbsolutePath());
            ObjectInputStream ois = new ObjectInputStream(is);
           ds.set((ArrayList<The>) ois.readObject());
           i=ds.size();
            JOptionPane.showMessageDialog(rootPane, "Đọc thành công");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(QuanLyThuVien.class.getName()).log(Level.SEVERE, null, ex);
                   JOptionPane.showMessageDialog(rootPane, "Đọc không thành công");

        } catch (IOException ex) {
            Logger.getLogger(QuanLyThuVien.class.getName()).log(Level.SEVERE, null, ex);
                   JOptionPane.showMessageDialog(rootPane, "Đọc không thành công");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyThuVien.class.getName()).log(Level.SEVERE, null, ex);
                           JOptionPane.showMessageDialog(rootPane, "Đọc không thành công");

        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(this);
        if (jfc.getSelectedFile()==null){
            JOptionPane.showMessageDialog(rootPane, "BẠN CHƯA CHỌN FILE NÀO ");
        }else{
        try {
            FileOutputStream os = new FileOutputStream(jfc.getSelectedFile().getAbsolutePath());
            ObjectOutputStream oos = new ObjectOutputStream(os);
            oos.writeObject(ds.getDS());
            oos.close();
            os.close();
            JOptionPane.showMessageDialog(rootPane, "GHI THÀNH CÔNG");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(QuanLyThuVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
           
            Logger.getLogger(QuanLyThuVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
public void dung(){
 
       model.setRowCount(0);
        for (The th: ds.getDS()){
           
            model.addRow(new Object[]{
        
    th.getMaPhieu(),th.getSinhVien().getHoTen(),th.getSinhVien().getTuoi(),th.getSinhVien().getLop(),th.getNgayMuon(),th.getNgayTra(),th.getSach().getMaSach(),th.getSach().getTenSach(),th.getSach().getTacGia()
    });
     table.setModel(model);
        }
}
    private void btnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowActionPerformed
        // TODO add your handling code here:
       ds.sapXep();
     dung();
    }//GEN-LAST:event_btnshowActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int selectedRow = table.getSelectedRow();
        jtextmaphieu.setText(model.getValueAt(selectedRow, 0).toString());
        jtextname.setText(model.getValueAt(selectedRow, 1).toString());
        jtexttuoi.setText(model.getValueAt(selectedRow, 2).toString());
        jtextlop.setText(model.getValueAt(selectedRow,3).toString());
        jtextday1.setText(model.getValueAt(selectedRow, 4).toString());
        jtextday2.setText(model.getValueAt(selectedRow, 5).toString());
        jtextmasach.setText(model.getValueAt(selectedRow, 6).toString());
        jtextnames.setText(model.getValueAt(selectedRow, 7).toString());
        jtextnametg.setText(model.getValueAt(selectedRow, 8).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        String ten= JOptionPane.showInputDialog("Nhập vào tên tác giả: ");
        if (ten!=null){
        model2.setRowCount(0);
         ArrayList<The> th= ds.getDS();
           int ok=0;
           for(The t:th){
            
            if ((t.getSach().getTacGia().toLowerCase()).contains(ten.toLowerCase())){
                
                model2.addRow(new Object[]{
                t.getSach().getMaSach(),t.getSach().getTenSach(),t.getSach().getTacGia()
                       
                });
                ok=1;
               table.setModel(model2);
            }
        }
           if  (ok==0){
            JOptionPane.showMessageDialog(rootPane, "TÊN SÁCH KHÔNG TỒN TẠI");
        }
        }
          
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jtextnametgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextnametgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextnametgActionPerformed

    public  The getthe(String ma){
        ArrayList<The> coppyThe=new ArrayList<>(ds.getDS());
        for (The the : coppyThe){
            if  (the.getMaPhieu().equals(ma)) return the;
        }
        return null;
    }
    
    public String maDeXoa;
    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
         maDeXoa=JOptionPane.showInputDialog(rootPane, "Nhập vào mã phiếu ");
        if (maDeXoa!=null){
            if (ds.check(maDeXoa)==true){
                JOptionPane.showMessageDialog(rootPane, "Mã thẻ không tồn tại");
            }else{
                
               
                The newthe=getthe(maDeXoa);
                jtextmaphieu.setText(newthe.getMaPhieu());
                jtextname.setText(newthe.getSinhVien().getHoTen());
                jtexttuoi.setText(newthe.getSinhVien().getTuoi()+"");
                jtextlop.setText(newthe.getSinhVien().getLop());
                jtextday1.setForeground(Color.black);
                jtextday1.setText(newthe.getNgayMuon());
                jtextday2.setForeground(Color.black);
                jtextday2.setText(newthe.getNgayTra());
                jtextmasach.setText(newthe.getSach().getMaSach());
                jtextnames.setText(newthe.getSach().getTenSach());
                jtextnametg.setText(newthe.getSach().getTenSach());
                btnthem.setText("UPDATE");
            }
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
          
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu OPEN;
    private javax.swing.JMenu SAVE;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnshow;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel hour12;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtextday1;
    private javax.swing.JTextField jtextday2;
    private javax.swing.JTextField jtextlop;
    private javax.swing.JTextField jtextmaphieu;
    private javax.swing.JTextField jtextmasach;
    private javax.swing.JTextField jtextname;
    private javax.swing.JTextField jtextnames;
    private javax.swing.JTextField jtextnametg;
    private javax.swing.JTextField jtexttuoi;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {            
            Calendar cal= Calendar.getInstance();
            hour=cal.get(cal.HOUR_OF_DAY);
            minute=cal.get(cal.MINUTE);
            second=cal.get(cal.SECOND);
            SimpleDateFormat sdf12 = new SimpleDateFormat("hh:mm:ss aa");
            Date dat = cal.getTime();
            String h12= sdf12.format(dat);
            hour12.setText(h12);
            
        }
    }
}
